### ISSUE TITLE
Points mutable problem with the current implmentation

### ISSUE THREAD

**Issue by dineshadepu** [ybyygu/rust-octree#2]
Thank you for the crate.  I just have a simple mutable reference problem.

As we can see Octree has a immutable reference to the `points`. Now say we have a simulation, where `points` will change their position with time. If the `octree` is active, then we will have a `mutable` reference problem, since `octree` has a mutable reference to the `points` and we are trying to `update` them.

How to deal with such a situation? Do you have any crate where you use this crate and solve did some simulation?

**Comment by ybyygu** [comment]
Thank you for your comments. This is a pratical issue when doing simulation, which can be resolved by borrowing the update strategy as in ASE's NeighborList module.

https://wiki.fysik.dtu.dk/ase/ase/neighborlist.html

I applied octree algorithm to build nearest neighbors in periodic system for better erformance than ASE, but not feature complete yet.

https://github.com/ybyygu/neighbors

Anyway, I plan to add this feature in the near furture.
